channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - ca-certificates=2025.1.31
  - libcxx
  - libffi=3.4.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libsqlite=3.46.0
  - libzlib=1.2.13
  - openssl=1.1.1w
  - pip=21.3.1
  - python=3.6.13
  - python_abi=3.6
  - setuptools=58.0.4
  - sqlite=3.46.0
  - tk=8.6.13
  - wheel=0.37.1
  - zlib=1.2.13
  - pip:
      - ./LIB/pyWinhook-1.6.1-cp36-cp36m-win_amd64.whl
      - ./LIB/ruamel.yaml.clib-0.2.7-cp36-cp36m-win_amd64.whl
      - ./LIB/psychtoolbox-3.0.19.0-cp36-cp36m-win_amd64.whl
      - arabic-reshaper==3.0.0
      - astunparse==1.6.3
      - certifi==2025.1.31
      - cffi==1.15.1
      - charset-normalizer==2.0.12
      - cycler==0.11.0
      - decorator==4.4.2
      - dukpy==0.2.3
      - esprima==4.0.1
      - et-xmlfile==1.1.0
      - freetype-py==2.2.0
      - future==1.0.0
      - gevent==22.10.2
      - gitdb==4.0.9
      - gitpython==3.1.18
      - glfw==2.9.0
      - greenlet==2.0.2
      - idna==3.10
      - imageio==2.15.0
      - imageio-ffmpeg==0.5.1
      - importlib-resources==5.4.0
      - javascripthon==0.13
      - jedi==0.19.2
      - json-tricks==3.17.3
      - kiwisolver==1.3.1
      - matplotlib==3.3.4
      - moviepy==1.0.3
      - msgpack==1.0.5
      - msgpack-numpy==0.4.8
      - numexpr==2.8.1
      - numpy==1.19.5
      - openpyxl==3.1.3
      - packaging==21.3
      - pandas==1.1.5
      - parso==0.8.4
      - pillow==8.4.0
      - proglog==0.1.11
      - psutil==7.0.0
      - psychopy==2021.1.3
      - pycparser==2.21
      - pyglet<1.5
      - pyopengl==3.1.9
      - pyosf==1.0.5
      - pyparsing==3.1.4
      - pyqt5==5.15.4
      - pyqt5-qt5>=5.15
      - pyqt5-sip==12.9.1
      - pyserial==3.5
      - python-bidi==0.4.2
      - python-dateutil==2.9.0.post0
      - python-gitlab==2.10.1
      - python-vlc==3.0.21203
      - pytz==2025.2
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - questplus==2019.4
      - requests==2.27.1
      - requests-toolbelt==1.0.0
      - scipy==1.5.4
      - six==1.17.0
      - smmap==5.0.0
      - sounddevice==0.4.4
      - soundfile==0.13.1
      - tables==3.7.0
      - tobii-research==1.8.0
      - tqdm==4.64.1
      - typing-extensions==4.1.1
      - ujson==4.3.0
      - urllib3==1.26.20
      - websocket-client==1.3.1
      - wxpython==4.0.6
      - xarray==0.16.2
      - xlrd==2.0.1
      - zipp==3.6.0
      - zope-event==4.6
      - zope-interface==5.5.2
      - --extra-index-url https://pypi.sr-support.com
      - sr-research-pylink==2.1.762.0
